import { Movie, Ranking, Quote, AppSettings, WatchLog } from '@/types';
import { nanoid } from 'nanoid';

const now = new Date().toISOString();
const year = new Date().getFullYear();

const createWatchLog = (movieId: string, date: string, note?: string): WatchLog => ({
  id: nanoid(),
  movieId,
  date,
  note,
  createdAt: now,
});

export const mockMovies: Movie[] = [
  {
    id: nanoid(),
    title: '奥本海默',
    originalTitle: 'Oppenheimer',
    year: 2023,
    genres: ['传记', '剧情', '历史'],
    director: '克里斯托弗·诺兰',
    cast: ['基里安·墨菲', '艾米莉·布朗特', '小罗伯特·唐尼'],
    runtime: 180,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=oppenheimer%20movie%20poster%20dramatic%20black%20and%20white%20atomic&image_size=portrait_4_3',
    country: '美国',
    rating: 9.2,
    status: 'watched',
    watchLogs: [createWatchLog('', `${year}-03-15`, '电影院IMAX')],
    shortReview: '诺兰的又一部神作，墨菲的表演令人震撼。',
    longReview: '这是一部关于人类命运的宏大叙事。诺兰用他标志性的非线性叙事，将奥本海默复杂的一生展现在观众面前...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '花月杀手',
    originalTitle: 'Killers of the Flower Moon',
    year: 2023,
    genres: ['犯罪', '剧情', '历史'],
    director: '马丁·斯科塞斯',
    cast: ['莱昂纳多·迪卡普里奥', '罗伯特·德尼罗', '莉莉·格莱斯顿'],
    runtime: 206,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=killers%20of%20the%20flower%20moon%20movie%20poster%20western%20dark&image_size=portrait_4_3',
    country: '美国',
    rating: 8.5,
    status: 'watched',
    watchLogs: [createWatchLog('', `${year}-02-20`)],
    shortReview: '斯科塞斯的西部史诗，沉重而深刻。',
    longReview: '这是一部关于贪婪与背叛的沉重史诗...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '坠落的审判',
    originalTitle: 'Anatomie d\'une chute',
    year: 2023,
    genres: ['剧情', '悬疑'],
    director: '茹斯汀·特里耶',
    cast: ['桑德拉·惠勒', '斯万·阿劳德', '米洛·马查多·格拉纳'],
    runtime: 151,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=anatomy%20of%20a%20fall%20movie%20poster%20courtroom%20drama%20moody&image_size=portrait_4_3',
    country: '法国',
    rating: 8.8,
    status: 'watched',
    watchLogs: [
      createWatchLog('', `${year}-04-10`, '电影节展映'),
      createWatchLog('', `${year}-08-15`, '二刷'),
    ],
    shortReview: '真相与谎言的边界，婚姻的解剖学。',
    longReview: '这不仅是一部法庭片，更是对婚姻关系的深度剖析...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '芭比',
    originalTitle: 'Barbie',
    year: 2023,
    genres: ['喜剧', '奇幻', '冒险'],
    director: '格蕾塔·葛韦格',
    cast: ['玛格特·罗比', '瑞恩·高斯林', '亚美莉卡·费雷拉'],
    runtime: 114,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=barbie%20movie%20poster%20pink%20dreamhouse%20vibrant&image_size=portrait_4_3',
    country: '美国',
    rating: 7.8,
    status: 'watched',
    watchLogs: [
      createWatchLog('', `${year}-07-22`, '和朋友一起'),
      createWatchLog('', `${year}-09-01`, '重看'),
      createWatchLog('', `${year}-12-25`, '圣诞夜'),
    ],
    shortReview: '粉色风暴下的女性主义宣言。',
    longReview: '芭比用一种轻松幽默的方式探讨了深刻的女性议题...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '流浪地球2',
    year: 2023,
    genres: ['科幻', '冒险', '灾难'],
    director: '郭帆',
    cast: ['吴京', '刘德华', '李雪健'],
    runtime: 173,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=wandering%20earth%202%20movie%20poster%20sci%20fi%20space%20epic&image_size=portrait_4_3',
    country: '中国',
    rating: 8.3,
    status: 'watched',
    watchLogs: [
      createWatchLog('', `${year}-01-25`, '大年初一'),
      createWatchLog('', `${year}-02-14`, '带家人二刷'),
    ],
    shortReview: '中国科幻的新高度。',
    longReview: '流浪地球2展现了中国科幻电影工业的成熟...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '蜘蛛侠：纵横宇宙',
    originalTitle: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    genres: ['动画', '动作', '冒险'],
    director: '乔伊姆·多斯·桑托斯',
    cast: ['沙梅克·摩尔', '海莉·斯坦菲尔德', '奥斯卡·伊萨克'],
    runtime: 140,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=spider-verse%20movie%20poster%20colorful%20animation%20multiverse&image_size=portrait_4_3',
    country: '美国',
    rating: 9.0,
    status: 'watched',
    watchLogs: [createWatchLog('', `${year}-06-05`)],
    shortReview: '视觉盛宴，动画艺术的巅峰。',
    longReview: '这是一部重新定义动画可能性的作品...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '过往人生',
    originalTitle: 'Past Lives',
    year: 2023,
    genres: ['剧情', '爱情'],
    director: '席琳·宋',
    cast: ['格蕾塔·李', '刘台午', '约翰·马加罗'],
    runtime: 106,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=past%20lives%20movie%20poster%20romantic%20dreamy%20soft%20light&image_size=portrait_4_3',
    country: '美国',
    rating: 8.6,
    status: 'watched',
    watchLogs: [createWatchLog('', `${year}-08-18`)],
    shortReview: '缘分与命运的温柔探讨。',
    longReview: '一部关于命运、缘分和选择的温柔电影...',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '利益区域',
    originalTitle: 'The Zone of Interest',
    year: 2023,
    genres: ['剧情', '历史', '战争'],
    director: '乔纳森·格雷泽',
    cast: ['桑德拉·惠勒', '克里斯蒂安·富里道尔'],
    runtime: 105,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=zone%20of%20interest%20movie%20poster%20holocaust%20drama%20ominous&image_size=portrait_4_3',
    country: '英国',
    rating: 8.4,
    status: 'watching',
    watchLogs: [],
    shortReview: undefined,
    longReview: undefined,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '怪物',
    originalTitle: '怪物',
    year: 2023,
    genres: ['剧情'],
    director: '是枝裕和',
    cast: ['安藤樱', '永山瑛太', '黑川想矢'],
    runtime: 125,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=monster%20movie%20poster%20japanese%20drama%20school%20mysterious&image_size=portrait_4_3',
    country: '日本',
    rating: 8.7,
    status: 'wish',
    watchLogs: [],
    shortReview: undefined,
    longReview: undefined,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '周处除三害',
    year: 2023,
    genres: ['动作', '犯罪', '剧情'],
    director: '黄精甫',
    cast: ['阮经天', '袁富华', '陈以文'],
    runtime: 130,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=the%20pig%20the%20snake%20and%20the%20pigeon%20movie%20poster%20taiwan%20gangster&image_size=portrait_4_3',
    country: '中国台湾',
    rating: 8.0,
    status: 'wish',
    watchLogs: [],
    shortReview: undefined,
    longReview: undefined,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '年少日记',
    year: 2023,
    genres: ['剧情'],
    director: '卓亦谦',
    cast: ['卢镇业', '郑中基', '陈汉娜'],
    runtime: 96,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=time%20still%20turns%20the%20pages%20movie%20poster%20hong%20kong%20drama%20nostalgic&image_size=portrait_4_3',
    country: '中国香港',
    rating: 8.2,
    status: 'dropped',
    watchLogs: [createWatchLog('', `${year}-05-10`, '看了一半')],
    shortReview: '题材不错但节奏稍慢。',
    longReview: undefined,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '可怜的东西',
    originalTitle: 'Poor Things',
    year: 2023,
    genres: ['剧情', '喜剧', '奇幻'],
    director: '欧格斯·兰斯莫斯',
    cast: ['艾玛·斯通', '马克·鲁法洛', '威廉·达福'],
    runtime: 141,
    poster: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=poor%20things%20movie%20poster%20surreal%20victorian%20whimsical&image_size=portrait_4_3',
    country: '英国',
    rating: 8.5,
    status: 'watched',
    watchLogs: [createWatchLog('', `${year}-09-12`)],
    shortReview: '荒诞又深刻的女性成长寓言。',
    longReview: '兰斯莫斯用他独特的荒诞风格讲述了一个女性觉醒的故事...',
    createdAt: now,
    updatedAt: now,
  },
];

mockMovies.forEach((movie) => {
  movie.watchLogs = movie.watchLogs.map((log) => ({ ...log, movieId: movie.id, id: nanoid() }));
});

export const mockRankings: Ranking[] = [
  {
    id: nanoid(),
    title: '2023年度十佳',
    description: '个人年度最佳影片榜单',
    isPublic: true,
    movieIds: mockMovies.filter(m => m.status === 'watched').slice(0, 5).map(m => m.id),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '科幻片单',
    description: '值得反复观看的科幻佳作',
    isPublic: false,
    movieIds: mockMovies.filter(m => m.genres.includes('科幻')).map(m => m.id),
    createdAt: now,
    updatedAt: now,
  },
  {
    id: nanoid(),
    title: '重看清单',
    description: '那些值得一看再看的电影',
    isPublic: true,
    movieIds: mockMovies.filter(m => m.watchLogs.length > 1).map(m => m.id),
    createdAt: now,
    updatedAt: now,
  },
];

export const mockQuotes: Quote[] = [
  {
    id: nanoid(),
    movieId: mockMovies[0].id,
    content: '我现在成为死神，世界的毁灭者。',
    note: '奥本海默引用 Bhagavad Gita',
    createdAt: now,
  },
  {
    id: nanoid(),
    movieId: mockMovies[3].id,
    content: '你很美。',
    note: '芭比对老太太说',
    createdAt: now,
  },
  {
    id: nanoid(),
    movieId: mockMovies[6].id,
    content: '如果命运是存在的，那它一定和你有关。',
    note: ' Past Lives',
    createdAt: now,
  },
];

export const mockSettings: AppSettings = {
  theme: 'dark',
  defaultYear: year,
  privacy: 'private',
};
